excluded:
  - .build
  - DerivedData

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil

line_length:
  warning: 120
  error: 150

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - x
    - y
    - i
    - n
    - t
